// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImgPalette = function() { };
LoadImgPalette.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImgPalette.index = 0;
		LoadImgPalette.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImgPalette.index = (LoadImgPalette.index - 1 + LoadImgPalette.images.length) % LoadImgPalette.images.length;
		LoadImgPalette.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImgPalette.index = (LoadImgPalette.index + 1) % LoadImgPalette.images.length;
		LoadImgPalette.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImgPalette.index = LoadImgPalette.images.length - 1;
		LoadImgPalette.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImgPalette.index = (LoadImgPalette.index - 1 + LoadImgPalette.images.length) % LoadImgPalette.images.length;
			LoadImgPalette.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImgPalette.index = (LoadImgPalette.index + 1) % LoadImgPalette.images.length;
			LoadImgPalette.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImgPalette.index = LoadImgPalette.images.length - 1;
			LoadImgPalette.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImgPalette.index = 0;
			LoadImgPalette.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	artwork.addEventListener("touchstart",function(e) {
		LoadImgPalette.startX = e.touches[0].clientX;
		LoadImgPalette.dragging = true;
	});
	artwork.addEventListener("touchmove",function(e) {
		if(LoadImgPalette.dragging) {
			LoadImgPalette.endX = e.touches[0].clientX;
		}
	});
	artwork.addEventListener("touchend",function(e) {
		if(LoadImgPalette.dragging) {
			LoadImgPalette.dragging = false;
			LoadImgPalette.handleSwipe(artwork,title);
		}
	});
	artwork.addEventListener("mousedown",function(e) {
		LoadImgPalette.startX = e.clientX;
		LoadImgPalette.dragging = true;
	});
	window.document.addEventListener("mousemove",function(e) {
		if(LoadImgPalette.dragging) {
			LoadImgPalette.endX = e.clientX;
		}
	});
	window.document.addEventListener("mouseup",function(e) {
		if(LoadImgPalette.dragging) {
			LoadImgPalette.dragging = false;
			LoadImgPalette.handleSwipe(artwork,title);
		}
	});
	LoadImgPalette.fadeUpdate(artwork,title);
};
LoadImgPalette.handleSwipe = function(artwork,title) {
	var diff = LoadImgPalette.endX - LoadImgPalette.startX;
	var threshold = 50;
	if(Math.abs(diff) < threshold) {
		return;
	}
	if(diff < 0) {
		LoadImgPalette.index = (LoadImgPalette.index + 1) % LoadImgPalette.images.length;
	} else {
		LoadImgPalette.index = (LoadImgPalette.index - 1 + LoadImgPalette.images.length) % LoadImgPalette.images.length;
	}
	LoadImgPalette.fadeUpdate(artwork,title);
};
LoadImgPalette.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImgPalette.images[LoadImgPalette.index].url;
		title.innerText = LoadImgPalette.images[LoadImgPalette.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImgPalette.images = [{ url : "../img/Welcome.png", title : "Portfolio Welcome"},{ url : "../img/IMG-20260224-WA0024.jpg", title : "Pink Rose"},{ url : "../img/IMG-20260224-WA0023.jpg", title : "Red Rose"},{ url : "../img/IMG-20260224-WA0022.jpg", title : "Image 1"},{ url : "../img/IMG-20260224-WA0021.jpg", title : "Image 2"},{ url : "../img/IMG-20260224-WA0020.jpg", title : "Image 3"},{ url : "../img/IMG-20260224-WA0019.jpg", title : "Image 4"},{ url : "../img/IMG-20260224-WA0018.jpg", title : "Image 5"},{ url : "../img/IMG-20260224-WA0017.jpg", title : "Image 6"},{ url : "../img/IMG-20260224-WA0016.jpg", title : "Image 7"},{ url : "../img/IMG-20260224-WA0014.jpg", title : "Image 8"},{ url : "../img/IMG-20260224-WA0012.jpg", title : "Image 9"},{ url : "../img/IMG-20260224-WA0010.jpg", title : "Image 10"},{ url : "../img/IMG-20260224-WA0008.jpg", title : "Image 11"},{ url : "../img/IMG-20260224-WA0007.jpg", title : "Image 12"},{ url : "../img/IMG-20260224-WA0006.jpg", title : "Image 13"},{ url : "../img/IMG-20260224-WA0005.jpg", title : "Image 14"},{ url : "../img/IMG-20260224-WA0004.jpg", title : "Image 15"},{ url : "../img/IMG-20260224-WA0003.jpg", title : "Image 16"},{ url : "../img/IMG-20260224-WA0002.jpg", title : "Image 17"},{ url : "../img/IMG-20260224-WA0001.jpg", title : "Image 18"}];
LoadImgPalette.index = 0;
LoadImgPalette.startX = 0;
LoadImgPalette.endX = 0;
LoadImgPalette.dragging = false;
LoadImgPalette.main();
})({});
